#!/bin/sh

set -x

libtoolize --force

# Only run aclocal if we need to create aclocal.m4
aclocal -I m4

# autoheader is smart and doesn't change anything unless it's necessary
autoheader
automake --foreign --add-missing --copy
autoconf
